title: "Jane Thao Nguyen"
description: "Writing Portfolio"
theme: jekyll-theme-dinky 

# Navigation menu
nav:
  - name: "Home"
    link: https://janengpersonal.github.io/portfolio/
  - name: "Docs"
    link: /samples/
  - name: "About"
    link: /about/

