title: "Jane Thao Nguyen"
description: "Writing Portfolio"
# Theme
remote_theme: poole/lanyon
plugins:
  - jekyll-remote-theme

# Optional settings
paginate: 5
paginate_path: "page:num"
markdown: kramdown
